package com.example.billingservice.feign;

import com.example.billingservice.model.Customer;
import feign.Headers;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.hateoas.PagedModel;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;

@FeignClient(name="CUSTOMER-SERVICE") // upper case obligatory
public interface CustomerRestClient {

    @GetMapping("/customers/{id}?projection=fullCustomer")
    public Customer customerById(@PathVariable Long id);
    //@Headers("Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIwMHhoaDV3YnlJb3d0Ti00ai12R1BPREhfVTBkOTVVREhPT2xKdGlNOGdrIn0.eyJleHAiOjE2NzE3NDI4MDUsImlhdCI6MTY3MTc0MjUwNSwianRpIjoiMjk2ZTJjYWYtNWM1MC00MjUzLWI1NzgtZGJhYTQ1YmU2ODE0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9lY29tLWNvbnRyb2wtcmVhbG0iLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiMjhlZjgwOTUtODUzMi00YWFmLWE3YWQtYjgwMmJlYjVlOTE0IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoicHJvZHVjdHMtYXBwIiwic2Vzc2lvbl9zdGF0ZSI6IjI4YzAwNzEwLTI3NTAtNGNiMS04Y2ExLTc4NzU0ODM3N2M0MSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJkZWZhdWx0LXJvbGVzLWVjb20tY29udHJvbC1yZWFsbSIsInVtYV9hdXRob3JpemF0aW9uIiwiQURNSU4iLCJVU0VSIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiMjhjMDA3MTAtMjc1MC00Y2IxLThjYTEtNzg3NTQ4Mzc3YzQxIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiSW1hbmUgUmFob3VpIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiaW1hbmUtcmFob3VpIiwiZ2l2ZW5fbmFtZSI6IkltYW5lIiwiZmFtaWx5X25hbWUiOiJSYWhvdWkiLCJlbWFpbCI6ImltYWFuZXJhaG91aUBnbWFpbC5jb20ifQ.Ks8EDyKzxeRsgBQC3obiA5_90TW1N3oHj3LrCihvysi5NJjrignOVLn4vdZvhtfSOsJX5rq0khfjer73W-ZfwUcxaWf6gFdh3GQ4qp0-3L9odPBH4WSK2Jj80KuwbBv2MnjGX7KmMc_dwVQe92kFZFhR5l0VkIE1f4GK_6zVZNZSTbIAqGuSvhGX6fPcs06qCzV5SlQ8M33T9RmyhwJV-HOo06rcCi-cRh5eO71qTPpfwAOTXz5FzwVMsNfy5Cq005Jez0DpUvSXB0OfSmVvgCpdcW3krbDR-cl9mixO5adKQUyPYIQHiLIBiXWcxWL0JkSeCymCSqxqm7OH_A1AtQ")
    @GetMapping("/customers?projection=fullCustomer")
    public PagedModel<Customer> allCustomers();

}
